steps:
#Execute SAST Scan using SonarCloud in GCP DevSecOps Pipeline
  - name: maven:3-openjdk-18-slim
    entrypoint: mvn
    args: ['verify', 'clean','build']
    id: SAST Scan using SonarCloud in GCP DevSecOps Pipeline
#Run DAST scan using OWASP ZAP in GCP DevSecOps Pipeline
  - name: 'ubuntu'
    entrypoint: bash
    args: 
      - '-c'
      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
        tar -xvf ZAP_2.14.0_Linux.tar.gz
        cd ZAP_2.14.0
        ./zap.sh -cmd -quickurl https://www.example.com -quickprogress 
    id: DAST Scan using OWASP ZAP
options:
  logging: CLOUD_LOGGING_ONLY
